# Generated by Django 4.1.6 on 2023-02-07 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Tipo de Equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('document', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Documento de Identidad')),
                ('firstname', models.CharField(max_length=20, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=20, verbose_name='Apellido')),
                ('address', models.CharField(blank=True, max_length=20, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('cellphone', models.CharField(blank=True, max_length=20, verbose_name='Celular')),
                ('email', models.CharField(blank=True, max_length=20, verbose_name='Correo Electrónico')),
                ('register', models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('serial', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Número de Serie')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.category')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('cellphone', models.CharField(blank=True, max_length=20, verbose_name='Celular')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Modelo')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reception', models.DateField(verbose_name='Fecha de Recepción')),
                ('time_reception', models.TimeField(verbose_name='Hora de Recepción')),
                ('details', models.TextField(max_length=1000, verbose_name='Descripción de Falla')),
                ('observations', models.TextField(blank=True, max_length=1000, verbose_name='Observaciones del Equipo')),
                ('date_repair', models.DateField(verbose_name='Fecha Prometida')),
                ('time_repair', models.TimeField(verbose_name='Hora Prometida')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_assignee', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer')),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.device')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.product'),
        ),
    ]
