# Generated by Django 4.1.6 on 2023-02-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_repair_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
